"""add chatbot icon fields to sites

Revision ID: f8e9d0a1b2c3
Revises: 03ea244985ce
Create Date: 2026-01-16 15:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e9d0a1b2c3'
down_revision = '3334862ee907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot_icon_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chatbot_icon', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chatbot_icon_background', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('chatbot_icon_background')
        batch_op.drop_column('chatbot_icon')
        batch_op.drop_column('chatbot_icon_type')

    # ### end Alembic commands ###
