"""add chatbot icon fields to site

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2026-01-16 15:12:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '03ea244985ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot_icon_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chatbot_icon', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chatbot_icon_background', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('chatbot_icon_background')
        batch_op.drop_column('chatbot_icon')
        batch_op.drop_column('chatbot_icon_type')

    # ### end Alembic commands ###
